{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubetruth.secretName" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "kubetruth.labels" . | nindent 4 }}
data:
  CLOUDTRUTH_API_KEY: {{ required "The cloudtruth api key needs to be set in .Values.appSettings.apiKey!" .Values.appSettings.apiKey | b64enc | quote }}
{{- end }}